[
  {
    "task_id": 8,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 52, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 0,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 4,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 3,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 19,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 10,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 6,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 78, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 42, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  }
]